from __future__ import annotations

from primordial.modes.security.execution_common import *


class PrimitiveAiReviewMixin:
    def _apply_ai_review(
        self,
        result: TaskExecutionResult,
        task: Task,
        ai_review: dict[str, object] | None,
    ) -> None:
        if not ai_review:
            task.metadata["ai_review_status"] = "unavailable"
            return
        note = ai_review.get("note")
        trace = ai_review.get("trace")
        proposal = ai_review.get("proposal")
        if isinstance(note, Note):
            result.notes.append(note)
        if isinstance(trace, AgentTrace):
            result.traces.append(trace)
        if isinstance(proposal, dict):
            task.metadata["ai_proposal"] = proposal
        task.metadata["ai_review_status"] = str(ai_review.get("status") or "completed")
        task.metadata["ai_review_attempted"] = True
        task.metadata["ai_model"] = ai_review.get("metadata", {}).get("model")
        task.metadata["ai_processor"] = ai_review.get("metadata", {}).get("processor")

    def _ai_review_requested(self, task: Task) -> bool:
        return bool(
            task.metadata.get("operator_triggered_ai_review")
            or task.metadata.get("allow_ai_review")
            or task.metadata.get("run_ai_review")
        )

    def _run_ai_review(
        self,
        task: Task,
        *,
        target_id: str | None,
        title: str,
        snapshot: str,
        instruction: str,
    ) -> dict[str, object] | None:
        if not self.ai_generate:
            return None
        system = (
            "You are a Primordial autonomous worker inside a policy-gated authorized security platform. "
            "Use only the supplied runtime snapshot. Be specific, evidence-backed, and operational. "
            "Never propose DoS, flooding, destructive actions, credential spraying, or unbounded brute force. "
            "If execution needs a missing primitive, state that as a capability gap instead of pretending it ran. "
            "Return a single JSON object only."
        )
        prompt = (
            f"Task: {task.kind.value}\n"
            f"Task title: {task.title}\n"
            f"Instruction: {instruction}\n\n"
            f"Runtime snapshot:\n{snapshot}\n\n"
            "Return JSON with keys:\n"
            "- summary: short operational summary\n"
            "- facts: list of concise evidence-backed facts\n"
            "- candidate_actions: list of objects with title, rationale, confidence, primitive_hint\n"
            "  Use exact primitive_hint values when applicable: content-discovery, http-probe, tcp-service-discovery.\n"
            "- blocked_reasons: list of concise blockers\n"
            "- required_primitives: list of missing or required primitive names\n"
            "- evidence_refs: list of evidence IDs if visible in the snapshot\n"
            "- confidence: float between 0 and 1\n"
            "- stop_conditions: list of explicit stop conditions or guardrails\n"
            "- capability_gaps: list of concrete missing capabilities\n"
            "Do not wrap the JSON in markdown fences."
        )
        response = self.ai_generate(task, system, prompt, 0.0)
        if not response or not response.get("text"):
            return None
        text = str(response["text"]).strip()
        proposal = self._parse_ai_review_json(text)
        status = "completed" if proposal is not None else "parse_failed"
        metadata = {
            "kind": "worker_ai_review",
            "task_kind": task.kind.value,
            "role_name": task.role.value if task.role else None,
            "stage": task.phase.value if task.phase else None,
            "model": response.get("model"),
            "elapsed_seconds": response.get("elapsed_seconds"),
            "prompt_tokens": response.get("prompt_tokens"),
            "completion_tokens": response.get("completion_tokens"),
            "retry_count": max(0, (task.attempts or 0) - 1),
            "num_gpu": response.get("num_gpu"),
            "processor": response.get("processor"),
            "structured_output": proposal is not None,
            "status": status,
        }
        note = None
        if target_id:
            note = Note(
                target_id=target_id,
                task_id=task.id,
                title=title,
                body=self._render_ai_review_note(proposal, text),
                confidence=0.72,
                freshness=0.95,
                metadata={**metadata, "proposal": proposal or {}},
            )
        trace = AgentTrace(
            task_id=task.id,
            role=task.role,
            status="ai_review_completed",
            summary=f"{title} generated by {response.get('model') or task.provider_model or 'local model'}",
            metadata={**metadata, "summary_key": f"{task.kind.value}:ai_review", "proposal": proposal or {}},
        )
        return {"note": note, "trace": trace, "metadata": metadata, "proposal": proposal, "status": status}

    def _build_ai_target_snapshot(self, target_id: str) -> str:
        target = self.store.get_target(target_id)
        active_generation = self._target_active_generation(target)
        evidence = self._records_for_generation(
            self.store.list_evidence(target_id=target_id, limit=24),
            active_generation,
        )
        interests = self._records_for_generation(
            self.store.list_interests(target_id=target_id, limit=12),
            active_generation,
        )
        findings = self._records_for_generation(
            self.store.list_findings(target_id=target_id, limit=8),
            active_generation,
        )
        tasks = self._task_records_for_generation(
            self.store.list_tasks(target_id=target_id, limit=20),
            active_generation,
        )
        lines = [
            f"Target: {target.handle if target else target_id}",
            f"Active generation: {active_generation or 'none'}",
            "Evidence:",
        ]
        lines.extend(
            f"- {item.id} | {item.title} | {item.verification_status.value} | confidence={item.confidence:.2f} | {item.summary[:500]}"
            for item in evidence
        )
        lines.append("Interests:")
        lines.extend(
            f"- {item.id} | {item.status.value} | confidence={item.confidence:.2f} | {item.title}: {item.summary[:350]}"
            for item in interests
        )
        lines.append("Findings:")
        lines.extend(
            f"- {item.id} | {item.severity.value} | {item.verification_status.value} | {item.title}: {item.summary[:350]}"
            for item in findings
        )
        lines.append("Recent tasks:")
        lines.extend(
            f"- {item.id} | {item.kind.value} | {item.status.value} | model={item.provider_model or 'unassigned'} | {item.title}"
            for item in tasks
        )
        return "\n".join(lines)

    def _build_ai_global_snapshot(self) -> str:
        targets = self.store.list_targets()
        tasks = self.store.list_tasks(limit=30)
        traces = self.store.list_traces(limit=20)
        lines = ["Targets:"]
        lines.extend(f"- {target.id} | {target.handle} | {target.profile.value} | in_scope={target.in_scope}" for target in targets)
        lines.append("Recent tasks:")
        lines.extend(f"- {task.id} | {task.kind.value} | {task.status.value} | {task.title}" for task in tasks)
        lines.append("Recent traces:")
        lines.extend(f"- {trace.id} | {trace.role.value} | {trace.status} | {trace.summary[:300]}" for trace in traces)
        return "\n".join(lines)

    def _fallback_target_id(self) -> str | None:
        targets = self.store.list_targets()
        return targets[0].id if targets else None

    def _parse_ai_review_json(self, text: str) -> dict[str, object] | None:
        candidate = text.strip()
        fenced = re.search(r"```(?:json)?\s*(\{.*\})\s*```", candidate, flags=re.DOTALL)
        if fenced:
            candidate = fenced.group(1)
        elif "{" in candidate and "}" in candidate:
            candidate = candidate[candidate.find("{") : candidate.rfind("}") + 1]
        try:
            payload = json.loads(candidate)
        except json.JSONDecodeError:
            return None
        if not isinstance(payload, dict):
            return None
        return {
            "summary": str(payload.get("summary", "")).strip(),
            "facts": self._normalize_string_list(payload.get("facts")),
            "candidate_actions": self._normalize_candidate_actions(payload.get("candidate_actions")),
            "blocked_reasons": self._normalize_string_list(payload.get("blocked_reasons")),
            "required_primitives": self._normalize_string_list(payload.get("required_primitives")),
            "evidence_refs": self._normalize_string_list(payload.get("evidence_refs")),
            "confidence": self._normalize_confidence(payload.get("confidence")),
            "stop_conditions": self._normalize_string_list(payload.get("stop_conditions")),
            "capability_gaps": self._normalize_string_list(payload.get("capability_gaps")),
        }

    def _render_ai_review_note(self, proposal: dict[str, object] | None, raw_text: str) -> str:
        if proposal is None:
            return raw_text
        lines = ["## Summary", str(proposal.get("summary") or "No summary provided.")]
        facts = proposal.get("facts", [])
        if isinstance(facts, list) and facts:
            lines.append("\n## Facts")
            lines.extend(f"- {item}" for item in facts[:8])
        candidate_actions = proposal.get("candidate_actions", [])
        if isinstance(candidate_actions, list) and candidate_actions:
            lines.append("\n## Candidate Actions")
            for item in candidate_actions[:6]:
                if not isinstance(item, dict):
                    continue
                title = str(item.get("title") or "untitled action")
                rationale = str(item.get("rationale") or "")
                confidence = item.get("confidence")
                primitive = str(item.get("primitive_hint") or "")
                suffix = []
                if confidence not in {None, ""}:
                    suffix.append(f"confidence={confidence}")
                if primitive:
                    suffix.append(f"primitive={primitive}")
                meta = f" ({', '.join(suffix)})" if suffix else ""
                lines.append(f"- {title}{meta}")
                if rationale:
                    lines.append(f"  {rationale}")
        blocked = proposal.get("blocked_reasons", [])
        if isinstance(blocked, list) and blocked:
            lines.append("\n## Blockers")
            lines.extend(f"- {item}" for item in blocked[:8])
        gaps = proposal.get("capability_gaps", [])
        if isinstance(gaps, list) and gaps:
            lines.append("\n## Capability Gaps")
            lines.extend(f"- {item}" for item in gaps[:8])
        stop_conditions = proposal.get("stop_conditions", [])
        if isinstance(stop_conditions, list) and stop_conditions:
            lines.append("\n## Stop Conditions")
            lines.extend(f"- {item}" for item in stop_conditions[:8])
        return "\n".join(lines)

    def _normalize_string_list(self, value: object) -> list[str]:
        if not isinstance(value, list):
            return []
        return [str(item).strip() for item in value if str(item).strip()][:12]

    def _normalize_candidate_actions(self, value: object) -> list[dict[str, object]]:
        if not isinstance(value, list):
            return []
        actions: list[dict[str, object]] = []
        for item in value[:8]:
            if isinstance(item, dict):
                actions.append(
                    {
                        "title": str(item.get("title", "")).strip(),
                        "rationale": str(item.get("rationale", "")).strip(),
                        "confidence": self._normalize_confidence(item.get("confidence")),
                        "primitive_hint": str(item.get("primitive_hint", "")).strip(),
                    }
                )
            elif str(item).strip():
                actions.append({"title": str(item).strip(), "rationale": "", "confidence": None, "primitive_hint": ""})
        return actions

    def _normalize_confidence(self, value: object) -> float | None:
        try:
            confidence = float(value)
        except (TypeError, ValueError):
            return None
        return max(0.0, min(1.0, confidence))
