#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml


DEFAULT_OUTPUT = "codex-goal.instruct"
DEFAULT_CURRENT = ".goal/current.json"
FRAGMENT_FILES = {
    "authority": "goal/fragments/authority.yaml",
    "environments": "goal/fragments/environments.yaml",
    "milestones": "goal/fragments/milestones.yaml",
    "run_profiles": "goal/fragments/run_profiles.yaml",
    "validation_tiers": "goal/fragments/validation_tiers.yaml",
    "report_contract": "goal/fragments/report_contract.yaml",
    "slices": "goal/slices.yaml",
}
SENSITIVE_CURRENT_KEYS = {
    "raw_target_evidence",
    "target_evidence",
    "secrets",
    "secret",
    "credentials",
    "credential",
    "flags",
    "flag",
    "raw_flags",
    "request_bodies",
    "request_body",
    "sensitive_payloads",
    "payload",
}
LAB_ONLY_ACTIONS = {"lab_solve_progression", "flag_collection"}
MILESTONE_STATUSES = {"not_started", "in_progress", "blocked", "fully_complete"}
DEFAULT_SLICE_RUN_LIMIT = 6


class GoalConfigError(ValueError):
    pass


def load_goal_config(root: Path) -> dict[str, Any]:
    return {name: _load_yaml(root / rel_path) for name, rel_path in FRAGMENT_FILES.items()}


def list_slice_packs(config: dict[str, Any]) -> list[dict[str, Any]]:
    return _as_list(config["slices"].get("slice_packs"))


def compile_slice_pack(root: Path, slice_pack_id: str, *, output: str = DEFAULT_OUTPUT) -> tuple[str, dict[str, Any]]:
    config = load_goal_config(root)
    errors = lint_config(config)
    if errors:
        raise GoalConfigError("\n".join(errors))

    slice_pack = _slice_pack_by_id(config, slice_pack_id)
    instruct = render_instruct(config, slice_pack)
    current = current_task_pointer(config, slice_pack, root=root, output=output, instruct=instruct)
    return instruct, current


def active_slice_pack_from_current(root: Path, current_output: str = DEFAULT_CURRENT) -> str:
    current_path = root / current_output
    try:
        payload = json.loads(current_path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise GoalConfigError(f"missing current task pointer: {current_path}") from exc
    except json.JSONDecodeError as exc:
        raise GoalConfigError(f"invalid current task pointer JSON: {current_path}") from exc
    if not isinstance(payload, dict):
        raise GoalConfigError(f"current task pointer must be a JSON object: {current_path}")
    slice_pack_id = str(payload.get("active_slice_pack", "")).strip()
    if not slice_pack_id:
        raise GoalConfigError("current task pointer missing active_slice_pack")
    forbidden = sorted(SENSITIVE_CURRENT_KEYS.intersection(payload.keys()))
    if forbidden:
        raise GoalConfigError(f"current task pointer contains sensitive keys: {', '.join(forbidden)}")
    return slice_pack_id


def render_instruct(config: dict[str, Any], slice_pack: dict[str, Any]) -> str:
    authority = config["authority"]
    environments = config["environments"]
    validation_tiers = config["validation_tiers"]
    report_contract = config["report_contract"]

    validation_tier = str(slice_pack["validation_tier"])
    validation = _by_id(_as_list(validation_tiers.get("validation_tiers")), validation_tier)
    source_refs = _as_list(slice_pack.get("source_refs")) or list(FRAGMENT_FILES.values())
    commands = _validation_commands(validation, slice_pack)
    coverage = milestone_coverage(config)
    slice_limit = _slice_run_limit(slice_pack)
    active_slices = _selected_slice_ids(slice_pack)
    next_pack = _next_slice_pack_id(config, str(slice_pack["id"]))
    active_pack_complete = _slice_pack_milestones_complete(config, slice_pack)

    lines: list[str] = [
        "/goal",
        "",
        "Generated by tools/goal_compile.py. Do not hand-edit durable policy here.",
        "",
        f"Active slice pack: {slice_pack['id']} - {slice_pack.get('title', '')}",
        f"Subsystem: {slice_pack.get('subsystem', '')}",
        f"Milestones: {', '.join(_as_text_list(slice_pack.get('milestones')))}",
        f"Validation tier: {validation_tier} ({validation.get('label', '')})",
        "",
        "Program milestone coverage:",
    ]
    lines.append(f"- Declared milestones: {', '.join(coverage['declared'])}")
    lines.append(f"- Slice-pack covered milestones: {', '.join(coverage['covered'])}")
    lines.append(f"- Missing slice-pack coverage: {', '.join(coverage['missing']) if coverage['missing'] else 'none'}")
    lines.append(
        f"- Fully complete milestones: {', '.join(coverage['fully_complete']) if coverage['fully_complete'] else 'none'}"
    )
    lines.append(
        f"- Not fully complete milestones: {', '.join(coverage['not_fully_complete']) if coverage['not_fully_complete'] else 'none'}"
    )
    lines.append(
        f"- Partially complete milestones: {', '.join(coverage['partially_complete']) if coverage['partially_complete'] else 'none'}"
    )
    lines.append(f"- Overall configured completion: {coverage['overall_completion_percent']}%")
    lines.append("- PROGRAM_DONE requires every typed milestone family to be implemented, evidenced, and validated.")
    lines.extend(
        [
            "",
            "Run completion contract:",
            "- This contract is for one bounded `/goal` invocation.",
            "- RUN_DONE closes this invocation after the selected run slices are validated and reported; it does not mean PROGRAM_DONE.",
            "- Do not self-continue after RUN_DONE. A later operator `/goal` run may use `python3 tools/goal_compile.py --advance` to select the next pack.",
            "- If validation completes this pack, update typed milestone evidence, run `python3 tools/goal_compile.py --advance`, re-read generated outputs, report the handoff, and stop.",
            "- PROGRAM_DONE remains reserved for all typed milestones being fully complete and validated.",
            f"- Active pack status in typed milestones: {'complete' if active_pack_complete else 'not complete'}.",
            f"- This active pack covers: {', '.join(_as_text_list(slice_pack.get('milestones')))}.",
        ]
    )
    lines.extend(
        [
            "",
            "Milestone progress:",
        ]
    )
    for milestone_id, progress in coverage["progress"].items():
        evidence = "; ".join(progress["evidence"][:2])
        evidence_suffix = f" (evidence: {evidence})" if evidence else " (evidence: none)"
        lines.append(
            f"- {milestone_id} {progress['completion_percent']}% {progress['status']} - "
            f"{progress['label']}{evidence_suffix}"
        )
    lines.extend(
        [
            "",
            "Source references:",
        ]
    )
    lines.extend(f"- {ref}" for ref in source_refs)

    lines.extend(
        [
            "",
            "Authority contract:",
        ]
    )
    lines.extend(f"- {rule['text']}" for rule in _as_list(authority.get("rules")))

    lines.extend(
        [
            "",
            "Environment routing:",
            "- Generic/unverified profile labels do not authorize stronger behavior.",
            "- Verified Hack The Box and local manifest-backed CTF/container labs may select stronger default intent.",
        ]
    )
    for env in _as_list(environments.get("environments")):
        lines.append(f"- {env['id']}: default_intent={env.get('default_intent')} verified_lab={env.get('verified_lab')}")

    lines.extend(
        [
            "",
            "Capability highlights:",
        ]
    )
    for cap in _as_list(environments.get("capabilities")):
        if cap.get("action") in {"lab_solve_progression", "credential_validation", "exploit_execution", "flag_collection"}:
            lines.append(f"- {cap['environment']}:{cap['action']} -> {cap['decision']}")

    lines.extend(
        [
            "",
            "Run batch:",
            f"- Max slices per run: {slice_limit}",
            f"- Active pack complete: {'yes' if active_pack_complete else 'no'}",
            f"- Advance-ready next slice pack: {next_pack if active_pack_complete and next_pack else 'none'}",
            "",
            "Selected run slices:",
        ]
    )
    lines.extend(f"- {slice_id}" for slice_id in active_slices)

    lines.extend(
        [
            "",
            "Slice pack rules:",
            f"- Work up to {DEFAULT_SLICE_RUN_LIMIT} related slices per run when they share subsystem, validation path, and authority model.",
            "- Do not run live AI inference, public PoCs, or real/public target actions.",
            "- Do not mutate live runtime data.",
            "- Preserve README.md as non-authoritative GitHub landing material.",
            "- Do not archive Markdown unless the active slice explicitly requires it.",
            "",
            "Expected files:",
        ]
    )
    lines.extend(f"- {path}" for path in _as_text_list(slice_pack.get("expected_files")))

    lines.extend(
        [
            "",
            "Validation commands:",
        ]
    )
    lines.extend(f"- {command}" for command in commands)

    lines.extend(
        [
            "",
            "Report contract:",
        ]
    )
    lines.extend(f"- {item}" for item in _as_text_list(report_contract.get("required_items")))
    lines.append("")
    lines.append(f"Next recommended slice pack: {slice_pack.get('next_action', '')}")
    lines.append("")
    lines.append(
        "Completion: stop after RUN_DONE for this bounded invocation; use PROGRAM_DONE only when all typed milestones are complete and validation is honestly reported."
    )
    return "\n".join(lines).rstrip() + "\n"


def lint_config(config: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    errors.extend(_lint_milestones(config["milestones"]))
    errors.extend(_lint_capabilities(config["environments"]))
    errors.extend(_lint_markdown_policy(config["environments"]))
    errors.extend(_lint_slice_packs(config))
    return errors


def current_task_pointer(
    config: dict[str, Any],
    slice_pack: dict[str, Any],
    *,
    root: Path,
    output: str,
    instruct: str,
) -> dict[str, Any]:
    coverage = milestone_coverage(config)
    next_pack = _next_slice_pack_id(config, str(slice_pack["id"]))
    active_pack_complete = _slice_pack_milestones_complete(config, slice_pack)
    current = {
        "active_slice_pack": slice_pack["id"],
        "selected_profile": slice_pack.get("run_profile", ""),
        "validation_tier": slice_pack.get("validation_tier", ""),
        "active_milestones": _as_text_list(slice_pack.get("milestones")),
        "active_slices": _selected_slice_ids(slice_pack),
        "slice_run_limit": _slice_run_limit(slice_pack),
        "declared_milestones": coverage["declared"],
        "covered_milestones": coverage["covered"],
        "missing_milestones": coverage["missing"],
        "fully_complete_milestones": coverage["fully_complete"],
        "partially_complete_milestones": coverage["partially_complete"],
        "not_fully_complete_milestones": coverage["not_fully_complete"],
        "milestone_progress": coverage["progress"],
        "overall_completion_percent": coverage["overall_completion_percent"],
        "active_pack_complete": active_pack_complete,
        "advance_ready": bool(active_pack_complete and next_pack),
        "next_slice_pack": next_pack,
        "generated_output_provenance": {
            output: _generated_output_provenance(root, output, instruct),
        },
        "expected_files": _as_text_list(slice_pack.get("expected_files")),
        "next_action": slice_pack.get("next_action", ""),
        "source_refs": _as_text_list(slice_pack.get("source_refs")),
    }
    forbidden = sorted(SENSITIVE_CURRENT_KEYS.intersection(current.keys()))
    if forbidden:
        raise GoalConfigError(f"current task pointer contains sensitive keys: {', '.join(forbidden)}")
    return current


def write_outputs(root: Path, instruct: str, current: dict[str, Any], *, output: str, current_output: str) -> None:
    output_path = root / output
    current_path = root / current_output
    output_path.write_text(instruct, encoding="utf-8")
    current_path.parent.mkdir(parents=True, exist_ok=True)
    current_path.write_text(json.dumps(current, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def verify_generated(root: Path, *, output: str = DEFAULT_OUTPUT, current_output: str = DEFAULT_CURRENT) -> list[str]:
    errors: list[str] = []
    slice_pack_id = active_slice_pack_from_current(root, current_output)
    expected_instruct, expected_current = compile_slice_pack(root, slice_pack_id, output=output)
    output_path = root / output
    current_path = root / current_output
    try:
        actual_instruct = output_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        errors.append(f"generated instruct missing: {output_path}")
    else:
        if actual_instruct != expected_instruct:
            errors.append(f"generated instruct is stale for active slice pack {slice_pack_id}; run --from-current")

    actual_current = _load_json_object(current_path, "current task pointer")
    for key in sorted(set(actual_current) - set(expected_current)):
        errors.append(f"current task pointer has stale extra field: {key}")
    for key in sorted(set(expected_current) - set(actual_current)):
        errors.append(f"current task pointer missing generated field: {key}")
    for key, expected_value in expected_current.items():
        if actual_current.get(key) != expected_value:
            errors.append(f"current task pointer field is stale: {key}")
    return errors


def _lint_capabilities(environments: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    decisions: dict[tuple[str, str], set[str]] = {}
    for capability in _as_list(environments.get("capabilities")):
        key = (str(capability.get("environment", "")), str(capability.get("action", "")))
        decisions.setdefault(key, set()).add(str(capability.get("decision", "")))
        if capability.get("environment") == "real_world" and capability.get("action") in LAB_ONLY_ACTIONS:
            if capability.get("decision") == "allow":
                errors.append(f"real_world cannot allow lab-only action by default: {capability.get('action')}")

    for (environment, action), values in sorted(decisions.items()):
        if "allow" in values and "block" in values:
            errors.append(f"conflicting capability decisions for {environment}:{action}: allow and block")

    for upgrade in _as_list(environments.get("profile_intent_upgrades")):
        intent = str(upgrade.get("default_intent", ""))
        if intent and intent != "recon_only" and not upgrade.get("requires_environment_proof"):
            profile = upgrade.get("profile", "<unknown>")
            errors.append(f"profile intent upgrade requires environment proof: {profile}")
        if intent and intent != "recon_only" and not upgrade.get("environment"):
            profile = upgrade.get("profile", "<unknown>")
            errors.append(f"profile intent upgrade requires environment class: {profile}")
    return errors


def _lint_markdown_policy(environments: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    for item in _as_list(_as_dict(environments.get("markdown_policy")).get("files")):
        path = str(item.get("path", ""))
        if path == "README.md" and item.get("authoritative"):
            errors.append("README.md must remain non-authoritative")
        if path.endswith(".md") and not item.get("exempt") and item.get("operational_rag_ingestible"):
            errors.append(f"non-exempt Markdown cannot be operational RAG ingestible: {path}")
    return errors


def _lint_milestones(milestones: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    for milestone in _as_list(milestones.get("milestones")):
        milestone_id = str(milestone.get("id", "<unknown>"))
        status = str(milestone.get("status", "")).strip()
        completion_percent = _completion_percent(milestone)
        if status not in MILESTONE_STATUSES:
            errors.append(f"unknown milestone status for {milestone_id}: {status}")
        if not 0 <= completion_percent <= 100:
            errors.append(f"milestone completion_percent must be 0-100 for {milestone_id}: {completion_percent}")
        if status == "fully_complete" and not _as_text_list(milestone.get("evidence")):
            errors.append(f"milestone completion evidence required: {milestone_id}")
        if status == "fully_complete" and completion_percent != 100:
            errors.append(f"fully complete milestone must be 100 percent: {milestone_id}")
        if status != "fully_complete" and completion_percent == 100:
            errors.append(f"only fully complete milestones may be 100 percent: {milestone_id}")
    return errors


def _lint_slice_packs(config: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    milestone_ids = {str(item.get("id")) for item in _as_list(config["milestones"].get("milestones"))}
    validation_tier_ids = {
        str(item.get("id")) for item in _as_list(config["validation_tiers"].get("validation_tiers"))
    }
    for pack in list_slice_packs(config):
        pack_id = str(pack.get("id", "<unknown>"))
        for milestone in _as_text_list(pack.get("milestones")):
            if milestone not in milestone_ids:
                errors.append(f"slice pack {pack_id} references unknown milestone id: {milestone}")
        validation_tier = str(pack.get("validation_tier", ""))
        if validation_tier not in validation_tier_ids:
            errors.append(f"slice pack {pack_id} references unknown validation tier id: {validation_tier}")

        slices = _as_list(pack.get("slices"))
        slice_limit = _configured_slice_run_limit(pack)
        if not 1 <= slice_limit <= DEFAULT_SLICE_RUN_LIMIT:
            errors.append(
                f"slice pack {pack_id} max_slices_per_run must be 1-{DEFAULT_SLICE_RUN_LIMIT}: {slice_limit}"
            )
        if len(slices) > slice_limit:
            errors.append(f"slice pack {pack_id} has more than {slice_limit} slices")
        subsystems = {str(item.get("subsystem", "")) for item in slices if isinstance(item, dict)}
        tiers = {str(item.get("validation_tier", "")) for item in slices if isinstance(item, dict)}
        if len(subsystems - {""}) > 1:
            errors.append(f"slice pack {pack_id} mixes subsystems: {', '.join(sorted(subsystems))}")
        if len(tiers - {""}) > 1:
            errors.append(f"slice pack {pack_id} mixes validation tiers: {', '.join(sorted(tiers))}")
    missing = milestone_coverage(config)["missing"]
    if missing:
        errors.append(f"milestones missing slice-pack coverage: {', '.join(missing)}")
    return errors


def milestone_coverage(config: dict[str, Any]) -> dict[str, Any]:
    milestone_items = _as_list(config["milestones"].get("milestones"))
    declared = sorted(str(item.get("id")) for item in milestone_items if item.get("id"))
    progress = {
        str(item["id"]): _milestone_progress(item)
        for item in sorted(milestone_items, key=lambda milestone: str(milestone.get("id", "")))
        if item.get("id")
    }
    fully_complete = sorted(
        milestone_id
        for milestone_id, item in progress.items()
        if item["status"] == "fully_complete" and item["completion_percent"] == 100 and item["evidence"]
    )
    partially_complete = sorted(
        milestone_id
        for milestone_id, item in progress.items()
        if milestone_id not in set(fully_complete) and item["completion_percent"] > 0
    )
    covered = sorted(
        {
            milestone
            for pack in list_slice_packs(config)
            for milestone in _as_text_list(pack.get("milestones"))
            if milestone in declared
        }
    )
    missing = [milestone for milestone in declared if milestone not in set(covered)]
    not_fully_complete = [milestone for milestone in declared if milestone not in set(fully_complete)]
    overall_completion_percent = round(
        sum(progress[milestone]["completion_percent"] for milestone in declared) / len(declared)
    ) if declared else 0
    return {
        "declared": declared,
        "covered": covered,
        "missing": missing,
        "fully_complete": fully_complete,
        "partially_complete": partially_complete,
        "not_fully_complete": not_fully_complete,
        "progress": progress,
        "overall_completion_percent": overall_completion_percent,
    }


def _slice_pack_by_id(config: dict[str, Any], slice_pack_id: str) -> dict[str, Any]:
    for pack in list_slice_packs(config):
        if pack.get("id") == slice_pack_id:
            return pack
    raise GoalConfigError(f"unknown slice pack: {slice_pack_id}")


def _validation_commands(validation: dict[str, Any], slice_pack: dict[str, Any]) -> list[str]:
    commands = _as_text_list(validation.get("commands"))
    test_command = _slice_pack_test_command(slice_pack)
    if test_command and test_command not in commands:
        commands.insert(0, test_command)
    return commands


def _slice_pack_test_command(slice_pack: dict[str, Any]) -> str:
    modules = [
        path[:-3].replace("/", ".")
        for path in _as_text_list(slice_pack.get("expected_files"))
        if path.startswith("tests/") and path.endswith(".py")
    ]
    modules = list(dict.fromkeys(modules))
    return f"python3 -m unittest {' '.join(modules)} -q" if modules else ""


def _selected_slice_ids(slice_pack: dict[str, Any]) -> list[str]:
    return [
        str(item.get("id"))
        for item in _as_list(slice_pack.get("slices"))[: _slice_run_limit(slice_pack)]
        if isinstance(item, dict) and item.get("id")
    ]


def _slice_run_limit(slice_pack: dict[str, Any]) -> int:
    return max(1, min(_configured_slice_run_limit(slice_pack), DEFAULT_SLICE_RUN_LIMIT))


def _configured_slice_run_limit(slice_pack: dict[str, Any]) -> int:
    try:
        return int(slice_pack.get("max_slices_per_run", DEFAULT_SLICE_RUN_LIMIT))
    except (TypeError, ValueError):
        return DEFAULT_SLICE_RUN_LIMIT + 1


def _slice_pack_milestones_complete(config: dict[str, Any], slice_pack: dict[str, Any]) -> bool:
    milestones = _as_text_list(slice_pack.get("milestones"))
    if not milestones:
        return False
    fully_complete = set(milestone_coverage(config)["fully_complete"])
    return all(milestone in fully_complete for milestone in milestones)


def _next_slice_pack_id(config: dict[str, Any], current_pack_id: str) -> str:
    packs = list_slice_packs(config)
    current_index = next((index for index, pack in enumerate(packs) if pack.get("id") == current_pack_id), None)
    if current_index is None:
        return ""
    candidates = packs[current_index + 1 :] + packs[:current_index]
    for pack in candidates:
        if not _slice_pack_milestones_complete(config, pack):
            return str(pack.get("id", ""))
    return ""


def _advance_slice_pack_id(config: dict[str, Any], current_pack_id: str) -> str:
    current_pack = _slice_pack_by_id(config, current_pack_id)
    if not _slice_pack_milestones_complete(config, current_pack):
        return current_pack_id
    return _next_slice_pack_id(config, current_pack_id) or current_pack_id


def _milestone_progress(milestone: dict[str, Any]) -> dict[str, Any]:
    return {
        "label": str(milestone.get("label", "")),
        "status": str(milestone.get("status", "")).strip(),
        "completion_percent": _completion_percent(milestone),
        "evidence": _as_text_list(milestone.get("evidence")),
    }


def _completion_percent(milestone: dict[str, Any]) -> int:
    default = 100 if str(milestone.get("status", "")).strip() == "fully_complete" else 0
    value = milestone.get("completion_percent", default)
    try:
        return int(value)
    except (TypeError, ValueError):
        return -1


def _generated_output_provenance(root: Path, output: str, instruct: str) -> dict[str, Any]:
    return {
        "generated_size_bytes": len(instruct.encode("utf-8")),
    }


def _by_id(items: list[dict[str, Any]], item_id: str) -> dict[str, Any]:
    for item in items:
        if item.get("id") == item_id:
            return item
    raise GoalConfigError(f"unknown id: {item_id}")


def _load_yaml(path: Path) -> dict[str, Any]:
    try:
        payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise GoalConfigError(f"missing goal source: {path}") from exc
    if not isinstance(payload, dict):
        raise GoalConfigError(f"goal source must be a mapping: {path}")
    return payload


def _load_json_object(path: Path, label: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise GoalConfigError(f"missing {label}: {path}") from exc
    except json.JSONDecodeError as exc:
        raise GoalConfigError(f"invalid {label} JSON: {path}") from exc
    if not isinstance(payload, dict):
        raise GoalConfigError(f"{label} must be a JSON object: {path}")
    return payload


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _as_text_list(value: Any) -> list[str]:
    return [str(item) for item in _as_list(value)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compile compact PRIMORDIAL goal instructions.")
    parser.add_argument("--root", default=".", help="Repository root containing goal/ fragments.")
    parser.add_argument("--list", action="store_true", help="List configured slice packs.")
    parser.add_argument("--slice-pack", help="Compile the selected slice pack.")
    parser.add_argument("--from-current", action="store_true", help="Compile the active slice pack from .goal/current.json.")
    parser.add_argument(
        "--advance",
        action="store_true",
        help="Compile the active slice pack unless it is complete, then advance to the next incomplete pack.",
    )
    parser.add_argument("--check", action="store_true", help="Validate goal fragments and slice packs.")
    parser.add_argument(
        "--verify-generated",
        action="store_true",
        help="Check that generated outputs match .goal/current.json without rewriting files.",
    )
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Generated instruct output path relative to root.")
    parser.add_argument(
        "--current-output",
        default=DEFAULT_CURRENT,
        help="Current task pointer output path relative to root.",
    )
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    try:
        if args.list:
            config = load_goal_config(root)
            for pack in list_slice_packs(config):
                print(f"{pack.get('id')}\t{pack.get('title', '')}")
            return 0
        if args.check:
            errors = lint_config(load_goal_config(root))
            if errors:
                for error in errors:
                    print(f"ERROR: {error}")
                return 1
            print("goal sources ok")
            return 0
        if args.verify_generated:
            errors = verify_generated(root, output=args.output, current_output=args.current_output)
            if errors:
                for error in errors:
                    print(f"ERROR: {error}")
                return 1
            print("generated goal outputs ok")
            return 0
        if args.slice_pack or args.from_current or args.advance:
            if args.advance:
                active_pack_id = active_slice_pack_from_current(root, args.current_output)
                slice_pack_id = _advance_slice_pack_id(load_goal_config(root), active_pack_id)
            else:
                slice_pack_id = args.slice_pack or active_slice_pack_from_current(root, args.current_output)
            instruct, current = compile_slice_pack(root, slice_pack_id, output=args.output)
            write_outputs(root, instruct, current, output=args.output, current_output=args.current_output)
            print(f"wrote {args.output}")
            print(f"wrote {args.current_output}")
            return 0
        parser.error("one of --list, --check, --verify-generated, --slice-pack, --from-current, or --advance is required")
    except GoalConfigError as exc:
        print(f"ERROR: {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
